### ISSUE TITLE
Unable to parse [ERROR]

### ISSUE THREAD

**Issue by Zwordi** [bjoernr-de/munin-mattermost#1]
Hello there,

So first issue on your repo.
Thank you for your scrip which i think can be really helpfull.
I follow your guide and made a test with a df test to send an alerts.

I never been able to have it working fine.
I got an error on the mattermost side 
CET] [EROR] /hooks/to8199i3kidk5eerp1w8jgz1ey:IncomingWebhookRequestFromJson code=400 rid=irkdfujsatfatfirhshx9gcydr uid= ip=*.*.*.* Unable to parse incoming data [details: invalid character '\\' after object key:value pair]

There is the command line which is sent by munin:
`
curl -s -o /dev/null -X POST -d 'payload={"channel":"Alerts", "username":"Munin Alert", "icon_url":"https://munin.tata.it/funny_crow.jpg", "text":"##### doc.tata.it - disk Disk usage in percent
| Category              | Value             |
|-----------------------|-------------------|
| Group                 | VMserver          |
| Host                  | doc.tata.it          |
| Munin graph category  | disk |
| Level                 | :grey_question: UNKNOWN       |
| Alert name            | Disk usage in percent    |

"\u000A* **WARNINGs**\u000A  * / is 64.45 "

https://munin.tata.it
https://munin.tata.tiVMserver/doc.tata.it#disk"}' https://chat.tata.it/hooks/to8199i3kidk5eerp1w8jgz1ey
`
What do you think ? How could i help?

Thanks
Zwordi

**Comment by bjoernr-de** [comment]
Hi @Zwordi

thanks for opening the first issue!
Glad to see someone's interested in the script :-)

Unfortunately it seems that the curl command part has not been formatted
properly as a code-block in GitHub.
Is it possible to share it again via GitHubGist or similar?

Can you also please share the Munin version and the OS you're using?

Thanks again and best regards,
Björn

**Comment by Zwordi** [comment]
Hello @bjoernr-de 

My OS version is debian 9.2.
My munin version is 2.0.33-1

https://gist.github.com/Zwordi/9e38cf66a11874bbc324d1f1e9dcb3d6

I put as much information as i courld think about.

Thanks for your feedback.
Zwordi

**Comment by bjoernr-de** [comment]
Hi @Zwordi 

thanks for the info. I use it in production with CentOS 6 and Debian 8.

Not sure why the `contact.mattermost.text` value is wrapped in quotes in the curl output.
```
"\u000A* **WARNINGs**\u000A  * / is 64.45 "
```
From first view it looks like that this is causing the JSON error.

I will go ahead and test it with your setup (Debian 9 and munin v2.0.33-1)

Best regards,
Björn

**Comment by bjoernr-de** [comment]
Hi @Zwordi 

thanks for the info. I use it in production with CentOS 6 and Debian 8.

I've seen that you wrapped the `contact.mattermost.text` command inside the `/etc/munin/munin.conf` with quotes.
(see https://gist.github.com/Zwordi/9e38cf66a11874bbc324d1f1e9dcb3d6#file-gistfile1-txt-L40)

Please remove the `"` in front and at the end according to the comment in https://github.com/bjoernr-de/munin-mattermost/blob/master/munin_mattermost_notify.sh#L13

Tested the script on Debian 9 with munin 2.0.33-1 and it's working fine 😃 

BTW if you want to force Munin to send an alert you can use the following command as root:
`su - munin --shell=/bin/bash -c "/usr/share/munin/munin-limits --contact mattermost --force"`
So you don't have to wait until the next cron run 😉 

Let me know if it works for you!

Best regards,
Björn

**Comment by Zwordi** [comment]
Perfect.
I just have the link to  MUNIN_URL/MUNIN_Groups uncorrect on the script.
Let me do the commit.

**Comment by Zwordi** [comment]
Ok i tried but unsucessfully to make a commit to your project. 
As i don't want to create a new branch:
On line 70 i added a / between ${MUNIN_URL} ${group}
${MUNIN_URL}/${group}/${host}/#${graph_category}

**Comment by bjoernr-de** [comment]
@Zwordi Regarding the URL:
Please see https://github.com/bjoernr-de/munin-mattermost/blob/master/munin_mattermost_notify.sh#L22 - It has a trailing slash 😃

**Comment by Zwordi** [comment]
Your right, but wouldn't be more simple to not let this trailing slash in order to avoid "simple" problem as the one i got ?
